[build]
  command = "npm run build"
  publish = ".next"

[functions]
  included_files = ["**/*.prisma", "**/*.so", "**/*.node"]
  external_node_modules = ["next"]
  node_bundler = "esbuild"
  node_bundler_exclude_files = [
    "node_modules/.cache/**",
    "node_modules/**/*.map",
    "node_modules/**/*.md"
  ]

[[redirects]]
  from = "/_next/image"
  query = { q = ":quality", url = ":url", w = ":width" }
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"

[[redirects]]
  from = "/_ipx/*"
  query = { q = ":quality", url = ":url", w = ":width" }
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
