# Build settings
[build]
  command = "npm run build"
  publish = ".next"

# Functions settings (Fixing duplicate key issue)
[functions]
  included_files = ["**/*.prisma", "**/*.so", "**/*.node"]
  node_bundler = "esbuild"
  external_node_modules = ["next"]

# Set Node.js version
[build.environment]
  NODE_VERSION = "18"

# Enable Netlify's Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect settings for Next.js images
[[redirects]]
  from = "/_next/image"
  query = { q = ":quality", url = ":url", w = ":width" }
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200